# Generated by Django 3.1.3 on 2020-12-28 10:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomApi', '0002_spaceship'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('image', models.TextField()),
                ('quantity', models.IntegerField()),
                ('price', models.IntegerField()),
                ('color', models.CharField(max_length=50)),
                ('date', models.DateField(default=datetime.date.today)),
                ('pricing', models.TextField()),
                ('status', models.BooleanField(default=False)),
            ],
        ),
        migrations.DeleteModel(
            name='Spaceship',
        ),
    ]
