# Generated by Django 3.1.3 on 2021-01-01 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomApi', '0005_auto_20201229_2111'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='Placement',
            field=models.TextField(null=True),
        ),
    ]
