# Generated by Django 3.1.3 on 2021-01-02 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomApi', '0007_auto_20210102_1347'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='user',
            field=models.CharField(default='null', max_length=50),
            preserve_default=False,
        ),
    ]
