# Generated by Django 3.1.3 on 2021-01-04 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomApi', '0008_orders_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='address',
            field=models.CharField(default='null', max_length=50),
        ),
        migrations.AddField(
            model_name='orders',
            name='quantities',
            field=models.IntegerField(default=1),
        ),
    ]
